sudo: required
services:
  - docker

before_install:
  - docker build -t wakeful_sun/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wakeful_sun/docker-react npm run test -- --coverage